#!/usr/bin/env bash

usage="$0 (setup|run)"
if [[ $# -ne 1 ]]; then
  1>&2 echo "$usage"
  exit 1
fi

timeout_duration="10"
mode="$1"
database_cluster_path="$HOME/data/projetos/lbaw1522/extra/postgresdb"

case "$mode" in
  "setup")
    timeout 10 echo "ola"
    echo $?
    timeout "$timeout_duration" killall postgres php --wait
    if [[ $? -eq 124 ]]; then
      1>&2 echo "killall timed out"
      exit 1
    elif [[ $? -eq 125 ]]; then
      1>&2 echo "timeout failed"
    fi

    # Create the database cluster and start postgresql
    rm -rf "$database_cluster_path"
    mkdir -p "$database_cluster_path"
    initdb --locale $LANG -E UTF8 -D "$database_cluster_path"
    postgres -D "$database_cluster_path" > /dev/null 2>&1 &
    cd "$database_cluster_path"
    createuser --superuser --pwprompt --echo admin
    createdb proto -U admin
    ;;
  "run")
    timeout "$timeout_duration" killall postgres php --wait
    if [[ $? -eq 124 ]]; then
      1>&2 echo "killall timed out"
      exit 1
    elif [[ $? -eq 125 ]]; then
      1>&2 echo "timeout failed"
    fi

    # Start php
    doc_root="$HOME/data/projetos/lbaw1522/Artefatos/A10"
    php -S localhost:8000 -t "$doc_root" > /dev/null 2>&1 &

    doc_root="$HOME/data/projetos/lbaw1522/extra/phppgAdmin"
    php -S localhost:8001 -t "$doc_root" > /dev/null 2>&1 &

    # Start postgresql
    postgres -D "$database_cluster_path" > /dev/null 2>&1 &
    ;;
  *)
    1>&2 echo "$usage"
    ;;
esac
